plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
layout: default
title: web絵　第15項/My painting record, paragraph 15.
description: PCで描いた絵をここに記録します。このサイトはダークモードにしたり、ブラウザーを変えると見え方が少し変わります。pc,androidのスペックでも絵が変化します。絵はほぼsvg形式で書かれています。
This is where I record the pictures I draw on my PC.This site looks a little different when you put it in dark mode or change browsers.The picture changes even with PC and Android specs.
The picture is written almost in SVG format.
lang: ja_JP
